import { Router, type IRouter } from "express";
import healthRouter from "./health";
import infoEuroRouter from "./inforeuro";
import tempMailRouter from "./tempmail";
import testimonialsRouter from "./testimonials";
import billingRouter from "./billing";
import authRouter from "./auth";
import meRouter from "./me";
import documentsRouter from "./documents";
import clientsRouter from "./clients";
import companyProfileRouter from "./companyProfile";
import usageRouter from "./usage";
import aiWriterRouter from "./aiwriter";
import contactRouter from "./contact";
import adminContactRouter from "./adminContact";
import adminRouter from "./admin";
import adminAnalyticsRouter from "./adminAnalytics";
import newsletterRouter from "./newsletter";
import adminNewsletterRouter from "./adminNewsletter";
import adminTestimonialsRouter from "./adminTestimonials";
import settingsRouter from "./settings";
import tasksRouter from "./tasks";
import activityRouter from "./activity";
import filesRouter from "./files";
import rfqRouter from "./rfq";
import rfqQuotesRouter from "./rfqQuotes";
import rfqSuppliersRouter from "./rfqSuppliers";

const router: IRouter = Router();

router.use(healthRouter);
router.use(infoEuroRouter);
router.use(tempMailRouter);
router.use(testimonialsRouter);
router.use(authRouter);
router.use(billingRouter);
router.use(meRouter);
router.use(documentsRouter);
router.use(clientsRouter);
router.use(companyProfileRouter);
router.use(usageRouter);
router.use(aiWriterRouter);
router.use(contactRouter);
router.use(adminContactRouter);
router.use(adminRouter);
router.use(adminAnalyticsRouter);
router.use(newsletterRouter);
router.use(adminNewsletterRouter);
router.use(adminTestimonialsRouter);
router.use(settingsRouter);
router.use(tasksRouter);
router.use(activityRouter);
router.use(filesRouter);
router.use(rfqRouter);
router.use(rfqQuotesRouter);
router.use(rfqSuppliersRouter);

export default router;
