// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/header/XuviloHeaderAnim.tsx": () => import("../components/mockups/header/XuviloHeaderAnim.tsx"),
  "./components/mockups/loading/XuviloLoadingAnim.tsx": () => import("../components/mockups/loading/XuviloLoadingAnim.tsx")
};
