import { AppLayout } from "@/components/layout/AppLayout";
import { SEOHead } from "@/components/SEOHead";
import { useLanguage } from "@/context/LanguageContext";

export default function TermsPage() {
  const { lang } = useLanguage();
  const isAR = lang === "ar";

  return (
    <AppLayout>
      <SEOHead
        title={isAR ? "شروط الاستخدام — Xuvilo" : "Terms of Use — Xuvilo"}
        description={
          isAR
            ? "شروط استخدام Xuvilo: قبول الشروط، استخدام الأدوات، مسؤوليات المستخدم، الملكية الفكرية، حدود المسؤولية، والقانون المعمول به."
            : "Xuvilo Terms of Use: acceptance of terms, use of tools, user responsibilities, intellectual property, limitation of liability, and governing law."
        }
        path="/terms"
      />

      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12 md:py-16">
        <article className="prose prose-gray dark:prose-invert max-w-none">
          <h1>{isAR ? "شروط الاستخدام" : "Terms of Use"}</h1>
          <p className="text-sm text-gray-500">{isAR ? "آخر تحديث: أبريل 2026" : "Last updated: April 2026"}</p>

          <h2>{isAR ? "1. قبول الشروط" : "1. Acceptance of terms"}</h2>
          <p>
            {isAR
              ? "باستخدامك لموقع Xuvilo (xuvilo.com) وأدواته، فإنك توافق على هذه الشروط. إذا لم توافق على أي جزء منها، فيرجى عدم استخدام الموقع."
              : "By using the Xuvilo website (xuvilo.com) and its tools, you agree to these terms. If you do not agree to any part, please do not use the site."}
          </p>

          <h2>{isAR ? "2. استخدام أدوات Xuvilo" : "2. Use of Xuvilo tools"}</h2>
          <p>
            {isAR
              ? "توفّر Xuvilo مجموعة من أدوات الأعمال المجانية والمدفوعة، بما في ذلك مولّد الفواتير، عروض الأسعار، الإيصالات، الحاسبات التجارية، وقوالب المستندات. الأدوات الأساسية متاحة دون الحاجة لإنشاء حساب."
              : "Xuvilo provides a suite of free and paid business tools, including an invoice generator, quotation generator, receipt generator, business calculators, and document templates. Core tools are available without creating an account."}
          </p>

          <h2>{isAR ? "3. مسؤولية المستخدم عن البيانات المُدخلة" : "3. User responsibility for entered data"}</h2>
          <p>
            {isAR
              ? "أنت المسؤول الوحيد عن دقة كل البيانات التي تُدخلها في أدوات Xuvilo. يجب على المستخدمين مراجعة كل الفواتير، عروض الأسعار، الإيصالات، الحسابات، قيم الضرائب، والمستندات التجارية والتحقق منها قبل استخدامها أو مشاركتها. Xuvilo ليست مسؤولة عن أي أخطاء ناتجة عن إدخال بيانات غير صحيحة."
              : "You are solely responsible for the accuracy of all data you enter into Xuvilo's tools. Users are responsible for reviewing and verifying all invoices, quotations, receipts, calculations, tax values, and business documents before using or sharing them. Xuvilo is not responsible for any errors resulting from incorrect data entry."}
          </p>

          <h2>{isAR ? "4. المستندات التجارية المُنشأة بواسطة Xuvilo" : "4. Business documents generated by Xuvilo"}</h2>
          <p>
            {isAR
              ? "أنت تحتفظ بالملكية الكاملة للمستندات التي تنشئها باستخدام أدواتنا. Xuvilo لا تدّعي أي حقوق في محتوى مستنداتك. تنبيه: يجب التأكد من أن مستنداتك تتوافق مع المتطلبات القانونية والضريبية في بلدك قبل إصدارها لعملائك."
              : "You retain full ownership of the documents you create using our tools. Xuvilo does not claim any rights to the content of your documents. Reminder: you must ensure your documents comply with the legal and tax requirements in your country before issuing them to your clients."}
          </p>

          <h2>{isAR ? "5. لا توجد مشورة قانونية، ضريبية، محاسبية، أو مالية" : "5. No legal, tax, accounting, or financial advice"}</h2>
          <p>
            {isAR
              ? "Xuvilo لا تقدّم مشورة قانونية أو ضريبية أو محاسبية أو مالية. أدواتنا وقوالبنا والمحتوى المعروض على الموقع هي للأغراض الإعلامية والتشغيلية العامة فقط. لقرارات تجارية أو قانونية أو ضريبية مهمة، استشر دائماً متخصصاً مؤهّلاً في ولايتك القضائية."
              : "Xuvilo does not provide legal, tax, accounting, or financial advice. Our tools, templates, and the content shown on the site are for general informational and operational purposes only. For important business, legal, or tax decisions, always consult a qualified professional in your jurisdiction."}
          </p>

          <h2>{isAR ? "6. إخلاء المسؤولية عن الدقة" : "6. Accuracy disclaimer"}</h2>
          <p>
            {isAR
              ? "نسعى جاهدين لجعل أدواتنا دقيقة ومحدّثة، لكننا لا نضمن خلوّها من الأخطاء أو ملاءمتها لكل ولاية قضائية. الحاسبات تقدّم تقديرات بناءً على المدخلات والقواعد الافتراضية المضمّنة، وقد لا تعكس آخر التغييرات في القوانين أو الأسعار."
              : "We strive to keep our tools accurate and up-to-date, but we do not guarantee they are error-free or fit for every jurisdiction. Calculators provide estimates based on inputs and built-in defaults, and may not reflect the latest changes in laws or rates."}
          </p>

          <h2>{isAR ? "7. الاستخدام المقبول" : "7. Acceptable use"}</h2>
          <p>{isAR ? "عند استخدام Xuvilo، توافق على عدم القيام بما يلي:" : "When using Xuvilo, you agree not to:"}</p>
          <ul>
            <li>{isAR ? "استخدام الموقع لأي نشاط غير قانوني أو احتيالي" : "Use the site for any illegal or fraudulent activity"}</li>
            <li>{isAR ? "إنشاء مستندات مزوّرة أو مضلّلة" : "Create forged or misleading documents"}</li>
            <li>{isAR ? "محاولة اختراق الموقع أو تعطيله أو الوصول غير المصرّح به" : "Attempt to hack, disrupt, or gain unauthorized access to the site"}</li>
            <li>{isAR ? "استخدام برامج آلية لإجهاد الخوادم أو سحب البيانات" : "Use automated tools to overload servers or scrape data"}</li>
            <li>{isAR ? "إعادة بيع الخدمة أو الوصول إليها بدون إذن صريح" : "Resell the service or access without explicit permission"}</li>
          </ul>

          <h2>{isAR ? "8. مسؤولية الحساب" : "8. Account responsibility"}</h2>
          <p>
            {isAR
              ? "إذا أنشأت حساباً، فأنت مسؤول عن الحفاظ على سرية بيانات تسجيل الدخول وعن جميع الأنشطة التي تتم باستخدام حسابك. أبلغنا فوراً عن أي استخدام غير مصرّح به."
              : "If you create an account, you are responsible for keeping your login credentials confidential and for all activity under your account. Notify us immediately of any unauthorized use."}
          </p>

          <h2>{isAR ? "9. الملكية الفكرية" : "9. Intellectual property"}</h2>
          <p>
            {isAR
              ? "موقع Xuvilo، بما في ذلك تصميمه، شعاره، الكود البرمجي، النصوص، والقوالب، مملوك لشركة Xuvilo. لا يجوز نسخ أو إعادة توزيع أو إعادة بيع أي جزء منه دون إذن كتابي مسبق. تحتفظ أنت بحقوق المستندات التي تنشئها باستخدام أدواتنا."
              : "The Xuvilo website, including its design, logo, code, text, and templates, is owned by Xuvilo. No part may be copied, redistributed, or resold without prior written permission. You retain the rights to documents you create using our tools."}
          </p>

          <h2>{isAR ? "10. حدود المسؤولية" : "10. Limitation of liability"}</h2>
          <p>
            {isAR
              ? "تُقدَّم Xuvilo \"كما هي\" ودون أي ضمانات صريحة أو ضمنية. إلى أقصى حد يسمح به القانون، لن تكون Xuvilo مسؤولة عن أي أضرار مباشرة أو غير مباشرة أو عرضية أو تبعية أو خاصة ناتجة عن استخدامك للموقع، بما في ذلك ولكن لا يقتصر على فقدان الأرباح، فقدان البيانات، أو توقّف الأعمال."
              : "Xuvilo is provided \"as is\" without any express or implied warranties. To the maximum extent permitted by law, Xuvilo shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from your use of the site, including but not limited to lost profits, data loss, or business interruption."}
          </p>

          <h2>{isAR ? "11. تغييرات على الخدمة" : "11. Changes to the service"}</h2>
          <p>
            {isAR
              ? "نحتفظ بالحق في تعديل، تعليق، أو إيقاف أي ميزة من ميزات الموقع في أي وقت ودون إشعار مسبق. لن نكون مسؤولين تجاه أي مستخدم أو طرف ثالث عن أي تعديل أو تعليق."
              : "We reserve the right to modify, suspend, or discontinue any feature of the site at any time without prior notice. We will not be liable to any user or third party for any modification or suspension."}
          </p>

          <h2>{isAR ? "12. الإنهاء" : "12. Termination"}</h2>
          <p>
            {isAR
              ? "يجوز لنا تعليق أو إنهاء وصولك إلى الخدمة في أي وقت إذا انتهكت هذه الشروط أو تصرفت بشكل يضرّ بالموقع أو بمستخدمين آخرين."
              : "We may suspend or terminate your access to the service at any time if you violate these terms or act in a way that harms the site or other users."}
          </p>

          <h2>{isAR ? "13. القانون المعمول به" : "13. Governing law"}</h2>
          <p>
            {isAR
              ? "تخضع هذه الشروط وتُفسَّر وفقاً للقوانين المعمول بها في الولاية القضائية التي تعمل بها Xuvilo. أي نزاع ينشأ من هذه الشروط أو يتعلق بها يخضع للاختصاص القضائي الحصري للمحاكم المختصة في تلك الولاية."
              : "These terms are governed by and construed in accordance with the applicable laws of the jurisdiction in which Xuvilo operates. Any dispute arising from or related to these terms is subject to the exclusive jurisdiction of the competent courts in that jurisdiction."}
          </p>

          <h2>{isAR ? "14. التواصل" : "14. Contact"}</h2>
          <p>
            {isAR ? "للاستفسارات القانونية أو المتعلقة بهذه الشروط، راسلنا على " : "For legal or terms-related inquiries, email us at "}
            <a href="mailto:support@xuvilo.com">support@xuvilo.com</a>.
          </p>
        </article>
      </div>
    </AppLayout>
  );
}
